# Generated by Django 5.2.6 on 2025-09-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectView',
        ),
    ]
