# Generated by Django 5.2.6 on 2025-09-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_projectview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
