# Generated by Django 5.2.6 on 2025-09-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skilltag_options_alter_skilltag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', through='core.ProjectSkill', to='core.skilltag'),
        ),
    ]
