# Generated by Django 5.2.6 on 2025-09-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
    ]
